FROM ruby:3.0.0

LABEL Name=simplescrabble Version=0.0.1

EXPOSE 3000

# throw errors if Gemfile has been modified since Gemfile.lock
RUN bundle config --global frozen 1

#add the working directory to the container
RUN mkdir /app
WORKDIR /app

#Copy the Gemfile and Gemfile.lock
COPY Gemfile Gemfile.lock ./

#Get the latest bundler version
RUN gem install bundler
#RUN gem install bundler:2.2.31

#The following line may be needed as I am developing on new Mac with Apple Chip
#RUN bundle lock --add-platform x86_64-linux

RUN bundle install

#Copy all files into the new app directory. Note: .dockerignore file ensures we are not copying secrets etc
COPY . /app

#CMD ["ruby", "simplescrabble.rb"]
CMD ["rails", "s" "-b", "0.0.0.0"]
